# backend/docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

  # backend:
  #   build: .
  #   container_name: backend
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   command: npm run dev

volumes:
  postgres-data:
